services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_DB: subscriptions_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    build: .
    container_name: subscription_tracker
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/subscriptions_db